# Generated by Django 2.0 on 2019-11-03 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redesocial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='redesocial.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='redesocial.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='redesocial.Address'),
        ),
    ]
